// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig, env } from 'prisma/config';

// Load .env.local first (for Next.js local development), then .env as fallback
config({ path: '.env.local' });
config({ path: '.env' });

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    // The migrate DSN. At TENANCY_MODE=multi the app connects as a restricted
    // NOBYPASSRLS role that does not own the tables, while migrations and seeds
    // keep the owner (BYPASSRLS) role: MIGRATE_DATABASE_URL names it and falls
    // back to DATABASE_URL, the single-tenant shape. See
    // .context/tenancy/isolation.md#the-role-split.
    url: process.env.MIGRATE_DATABASE_URL ? env('MIGRATE_DATABASE_URL') : env('DATABASE_URL'),
  },
});
